project/job/urls.py
from django.urls import path

from . import views

app_name = 'job'

urlpatterns = [
    path('management/', views.JobManagement.as_view(), name='management'),
    path(
        'application_management/',
        views.ApplicationManagement.as_view(),
        name='application_management',
    ),
    path(
        'application/<slug:slug>',
        views.JobApplication.as_view(),
        name='application',
    ),
    path('list/', views.JobList.as_view(), name='list'),
    path('create/', views.JobCreate.as_view(), name='create'),
    path('detail/<slug:slug>', views.JobDetail.as_view(), name='detail'),
    path('update/<slug:slug>', views.JobUpdate.as_view(), name='update'),
    path('delete/<slug:slug>', views.JobDelete.as_view(), name='delete'),
    path('search/', views.JobSearch.as_view(), name='search'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('project.common.urls')),
    path('account/', include('project.account.urls')),
    path('job/', include('project.job.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

project/job/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _

from project.roles import *


class Base(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_('created at')
    )
    updated_on = models.DateTimeField(
        auto_now=True, verbose_name=_('updated on')
    )

    class Meta:
        abstract = True


class Schooling(models.Model):
    schooling = models.CharField(
        max_length=30, unique=True, verbose_name=_('schooling')
    )
    level = models.PositiveIntegerField(verbose_name=_('level'))

    def __str__(self) -> str:
        return self.schooling

    def __gt__(self, obj):
        if self.level > obj.level:
            return True
        return False

    def __ge__(self, obj):
        if self.level >= obj.level:
            return True
        return False

    def __eq__(self, obj):
        if self.level == obj.level:
            return True
        return False

    class Meta:
        verbose_name = _('schooling')
        verbose_name_plural = _('schoolings')


class Job(Base):
    title = models.CharField(max_length=100, verbose_name=_('title'))
    status = models.BooleanField(default=False)
    checked = models.BooleanField(default=False)
    slug = models.SlugField(unique=True, verbose_name=_('friendly url'))
    schooling = models.ForeignKey(
        to=Schooling, on_delete=models.DO_NOTHING, verbose_name=_('schooling')
    )
    salary_from = models.DecimalField(
        max_digits=20,
        decimal_places=2,
        default=0,
        validators=[MinValueValidator(0.0)],
        verbose_name=_('salary from'),
    )
    salary_to = models.DecimalField(
        max_digits=20,
        decimal_places=2,
        default=0,
        validators=[MinValueValidator(0.0)],
        verbose_name=_('salary to'),
    )
    company = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        limit_choices_to=Q(groups__name=Company.get_name()),
        on_delete=models.CASCADE,
        verbose_name=_('company'),
    )
    description = models.TextField(
        max_length=500, verbose_name=_('description')
    )

    def __str__(self) -> str:
        return self.title

    def clean(self):
        if self.salary_from > self.salary_to:
            raise ValidationError(
                _('"salary to" cannot be less than "salary from"')
            )

    class Meta:
        verbose_name = _('job')


class Application(Base):
    status = models.BooleanField(default=True)
    job = models.ForeignKey(
        to=Job, on_delete=models.CASCADE, verbose_name=_('job')
    )
    candidate = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        limit_choices_to={'groups__name': Candidate.get_name()},
        on_delete=models.CASCADE,
        verbose_name=_('candidate'),
    )
    salary_expectation = models.DecimalField(
        max_digits=20,
        decimal_places=2,
        validators=[MinValueValidator(0.0)],
        verbose_name=_('salary expectation'),
    )

    score = models.DecimalField(
        max_digits=4,
        decimal_places=2,
        validators=[MinValueValidator(0.0)],
        verbose_name=_('score'),
    )

    def calculate_score(self):
        profile = self.candidate.profilecandidate
        max_score = 100
        max_parity = 2
        candidate_parity = 0

        if profile.schooling is not None:
            if profile.schooling >= self.job.schooling:
                candidate_parity += 1

        if self.job.salary_to >= self.salary_expectation:
            candidate_parity += 1

        score = max_score / max_parity * candidate_parity

        return score

    def save(self, *args, **kwargs):
        self.score = self.calculate_score()
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.job.title

    def unique_error_message(self, model_class, unique_check):
        error = super().unique_error_message(model_class, unique_check)

        if model_class == type(self) and unique_check == ('candidate', 'job'):
            error.message = _('%(candidate)s already registered for job.')
            error.params['candidate'] = self.candidate

        return error

    class Meta:
        verbose_name = _('application')
        unique_together = ['candidate', 'job']

project/job/forms/base_model_form.py
from django.forms import ModelForm


class BaseModelForm(ModelForm):
    def add_attr(self, field, attr_name, attr_value):
        field = self.fields[field]
        existing_attr = field.widget.attrs.get(attr_name, '')
        field.widget.attrs[attr_name] = f'{existing_attr} {attr_value}'.strip()

    def add_attr_placeholder(self, field, attr_value):
        self.add_attr(field, 'placeholder', attr_value)

project/job/forms/job_application.py
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from project.job.models import Application


class JobApplicationForm(ModelForm):
    class Meta:
        model = Application
        exclude = ['job', 'candidate', 'status', 'score']

project/job/forms/job_create.py
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from project.job.mixins import FormMixin
from project.job.models import Job


class JobCreateForm(FormMixin, ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.add_attr_placeholder('title', _('job title'))

    class Meta:
        model = Job
        exclude = ('company',)

project/job/forms/job_update.py
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from project.job.mixins import FormMixin
from project.job.models import Job


class JobUpdateForm(FormMixin, ModelForm):
    class Meta:
        model = Job
        fields = ('status',)

project/job/views/application.py
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView
from rolepermissions.mixins import HasRoleMixin

from project.job import facade
from project.job.forms import JobApplicationForm
from project.roles import Candidate


class JobApplication(HasRoleMixin, SuccessMessageMixin, CreateView):
    form_class = JobApplicationForm
    template_name = 'job/job_form.html'
    extra_context = {'title': _('job application')}
    success_url = reverse_lazy('job:application_management')
    success_message = _('Enrollment successful')
    allowed_roles = Candidate.get_name()

    def get(self, request, *args, **kwargs):
        try:
            facade.get_job_activated_authorized_with_slug(self.kwargs['slug'])
            return super().get(request, *args, **kwargs)
        except facade.JobDoesNotExist:
            raise Http404()

    def form_valid(self, form):
        try:
            job = facade.get_job_activated_authorized_with_slug(
                self.kwargs['slug']
            )
            form.instance.candidate = self.request.user
            form.instance.job = job
            return super().form_valid(form)
        except facade.JobDoesNotExist:
            raise Http404()

project/job/views/application_management.py
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView
from rolepermissions.mixins import HasRoleMixin

from project.job import facade
from project.roles import Candidate


class ApplicationManagement(HasRoleMixin, ListView):
    template_name = 'job/application_management.html'
    allowed_roles = Candidate.get_name()
    extra_context = {'title': _('application management')}

    def get_queryset(self):
        self.queryset = facade.get_user_application_list(
            user=self.request.user
        )
        return super().get_queryset()

project/job/views/create.py
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView
from rolepermissions.mixins import HasRoleMixin

from project.job.forms import JobCreateForm
from project.roles import Company


class JobCreate(HasRoleMixin, CreateView):
    template_name = 'job/job_form.html'
    form_class = JobCreateForm
    extra_context = {'tittle': _('job registration')}
    allowed_roles = Company.get_name()

project/job/views/delete.py
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import DeleteView
from rolepermissions.mixins import HasRoleMixin

from project.job import facade
from project.roles import Company


class JobDelete(HasRoleMixin, DeleteView):
    success_url = reverse_lazy('job:management')
    queryset = facade.get_full_job_list()
    allowed_roles = Company.get_name()

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.company != self.request.user:
            return HttpResponse('Unauthorized', status=401)
        return super().dispatch(request, *args, **kwargs)

project/job/views/detail.py
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView

from project.job import facade


class JobDetail(DetailView):
    template_name = 'job/job_detail.html'
    extra_context = {'tittle': _('job detail')}
    queryset = facade.get_authorized_job_list()

project/job/views/job_management.py
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView
from rolepermissions.mixins import HasRoleMixin

from project.job import facade
from project.roles import Company


class JobManagement(HasRoleMixin, ListView):
    template_name = 'job/job_management.html'
    allowed_roles = Company.get_name()
    extra_context = {'title': _('job management')}

    def get_queryset(self):
        self.queryset = facade.get_user_job_list(user=self.request.user)
        return super().get_queryset()

project/job/views/list.py
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView

from project.job import facade


class JobList(ListView):
    template_name = 'job/job_list.html'
    extra_context = {'tittle': _('job list')}
    paginate_by = settings.PER_PAGE
    queryset = facade.get_activated_authorized_job_list()

project/job/views/management.py
from django.views.generic import ListView

from project.job import facade


class JobManagement(ListView):
    template_name = 'job/job_management.html'

    def get_queryset(self):
        return facade.get_user_job_list(user=self.request.user)

project/job/views/search.py
from django.conf import settings
from django.db.models import Q
from django.http import Http404
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView

from project.job import facade


class JobSearch(ListView):
    template_name = 'job/job_list.html'
    extra_context = {'title': _('search')}
    paginate_by = settings.PER_PAGE
    ordering = '-created_at'

    def get_queryset(self):
        search_term = self.request.GET.get('q', '').strip()

        if not search_term:
            raise Http404()

        self.queryset = facade.get_activated_authorized_job_list().filter(
            Q(title__icontains=search_term)
            | Q(description__icontains=search_term)
        )

        return super().get_queryset()

project/job/views/update.py
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import UpdateView

from project.job import facade
from project.job.forms import JobUpdateForm


class JobUpdate(UpdateView):
    success_url = reverse_lazy('job:management')
    queryset = facade.get_full_job_list()
    form_class = JobUpdateForm
    template_name = 'job/job_form.html'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.company != self.request.user:
            return HttpResponse('Unauthorized', status=401)
        return super().dispatch(request, *args, **kwargs)

project/job/templates/job/application_management.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}

<div class="content-box">
    <table class="table table-striped table-dark table-bordered">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">{% translate "job title" %}</th>
                <th scope="col">{% translate "application date" %}</th>
                <th scope="col" class="text-center">{% translate "status" %}</th>
                <th scope="col" class="text-center">{% translate "cancel" %}</th>
            </tr>
        </thead>
        <tbody>
        {% for application in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ application.job.title }}</td>
                <td>{{ application.job.created_at }}</td>
                <td class="text-center">
                    {% if application.job.status == False %}
                    {% translate "inactive" %}
                    {% else %}
                    {% translate "active" %}
                    {% endif %}
                </td>
                <td class="text-center">
                    <form method="post" >{% csrf_token %}
                        <input class='input-delete' type="submit" value="{% translate "delete" %}" job="{{ application.job.title }}">
                    </form>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}
{% block footer %}
<script>
window.onload = ()=>{
    document.querySelectorAll('.input-delete').forEach(input=>{
        let job_title = input.getAttribute('job')
        input.addEventListener('click', event=>{
            event.preventDefault()
            const confirmed = confirm(`{% translate "Are you sure you want to cancel the application in job" %} "${job_title}" ?`)
            
            if (confirmed) {
                input.parentElement.submit()
            }
        })
    })
}
</script>
{% endblock footer %}

project/job/templates/job/job_detail.html
<p>{{ object.title }}</p>
<p>{{ object.description }}</p>
<p>{{ object.status }}</p>

project/job/templates/job/job_form.html
{% extends 'base.html' %}
{% block content %}
<form action="" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="aplicar">
</form>
{% endblock content %}

project/job/templates/job/job_list.html
{% extends 'base.html' %}
{% block content %}
<div>
{% for object in object_list %}
    <p>{{ object.title }}</p>
{% endfor %}
</div>
{% endblock content %}

project/job/templates/job/job_management.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}

<div class="content-box">
    <table class="table table-striped table-dark table-bordered">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">{% translate "job title" %}</th>
                <th scope="col">{% translate "posting date" %}</th>
                <th scope="col" class="text-center">{% translate "status" %}</th>
                <th scope="col" class="text-center">{% translate "registrations" %}</th>
                <th scope="col" class="text-center">{% translate "delete" %}</th>
            </tr>
        </thead>
        <tbody>
        {% for job in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ job.title }}</td>
                <td>{{ job.created_at }}</td>
                <td class="text-center">
                    {% if job.status == False %}
                    {% translate "inactive" %}
                    {% else %}
                    {% translate "active" %}
                    {% endif %}
                </td>
                <td class="text-center">{{ job.application_set.count }}</td>
                <td class="text-center">
                    <form method="post" action="{% url 'job:delete' job.slug %}">{% csrf_token %}
                        <input class='input-delete' type="submit" value="{% translate "delete" %}" job="{{ job.title }}">
                    </form>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}
{% block footer %}
<script>
window.onload = ()=>{
    document.querySelectorAll('.input-delete').forEach(input=>{
        let job_title = input.getAttribute('job')
        input.addEventListener('click', event=>{
            event.preventDefault()
            const confirmed = confirm(`{% translate "Are you sure you want to delete the job" %} "${job_title}" ?`)
            
            if (confirmed) {
                input.parentElement.submit()
            }
        })
    })
}
</script>
{% endblock footer %}